const REQUEST_PUPPETS_FAILED = 'REQUEST_PUPPETS_FAILED';
const REQUEST_PUPPETS_PENDING = 'REQUEST_PUPPETS_PENDING';
const REQUEST_PUPPETS_SUCCESS = 'REQUEST_PUPPETS_SUCCESS';
const CHANGE_FONT_SCALE = 'CHANGE_FONT_SCALE';

export {
  REQUEST_PUPPETS_SUCCESS,
  REQUEST_PUPPETS_PENDING,
  REQUEST_PUPPETS_FAILED,
  CHANGE_FONT_SCALE
};
